// Stamp the build so "is this the right build?" is answerable by looking.
//
// Studio snapshots the .rbxl when you open it and never re-reads it, so rojo
// rewriting the file underneath an open session changes nothing -- the place
// keeps running whatever it was opened with. That has now produced two rounds
// of "why isn't my change here", and neither time was anything actually wrong
// with the build: check-luau's staleness guard compares the .rbxl to game-src
// and was perfectly happy, because it cannot see what Studio is holding in
// memory.
//
// So the place says what it is, in the output window, every single run.
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const OUT = path.join(ROOT, 'game-src/shared/BuildInfo.luau');

const git = (args, fallback) => {
  try {
    return execFileSync('git', args, { cwd: ROOT, encoding: 'utf8' }).trim();
  } catch {
    return fallback;
  }
};

const sha = git(['rev-parse', '--short', 'HEAD'], 'unknown');
const branch = git(['rev-parse', '--abbrev-ref', 'HEAD'], 'unknown');
const dirty = git(['status', '--porcelain'], '') !== '' ? '+dirty' : '';
// Local time, because the person reading it is sitting in front of the clock
// they are comparing it against.
const at = new Date().toLocaleString('sv-SE').slice(0, 16);

const lua = `--!strict
-- GENERATED by tools/stamp-build.mjs at build time -- do not edit, do not commit.
--
-- Exists so a running place can tell you which build it is. Studio holds the
-- .rbxl it was opened with for the life of the session, so the only reliable
-- way to know what you are playing is to ask it.
return {
\tsha = "${sha}${dirty}",
\tbranch = "${branch}",
\tbuiltAt = "${at}",
\tsummary = "${sha}${dirty} on ${branch}, built ${at}",
}
`;

fs.writeFileSync(OUT, lua);
console.log(`stamped ${sha}${dirty} on ${branch} (${at})`);
