// hat-fits.json -> ../roblox-game/game-src/client/HatFits.luau
import fs from 'node:fs';
import path from 'node:path';

const DIR = path.dirname(new URL(import.meta.url).pathname);
const fits = JSON.parse(fs.readFileSync(path.join(DIR, 'hat-fits.json'), 'utf8'));

const luaValue = (v) => {
  if (Array.isArray(v)) return `{ ${v.map(luaValue).join(', ')} }`;
  if (typeof v === 'object') {
    return `{ ${Object.entries(v)
      .filter(([k]) => k !== 'COMMENT')
      .map(([k, val]) => `["${k}"] = ${luaValue(val)}`)
      .join(', ')} }`;
  }
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  return String(v);
};

const lua = `--!strict
-- GENERATED by roblox/gen-hatfits.mjs from roblox/hat-fits.json — do not
-- edit. Per-(hat x species) cosmetic fit registry: scale/offset/tilt and
-- feature policy. The turnaround sheets read the same JSON.
local DATA = ${luaValue({ defaults: fits.defaults, species: fits.species })}

local HatFits = {}

export type Fit = { scale: number, offset: Vector3, tilt: CFrame, hideEars: boolean }

function HatFits.resolve(skin: string, hatId: string): Fit
	local merged = { scale = 1, offset = { 0, 0, 0 }, tilt = { 0, 0 }, hideEars = false }
	for k, v in DATA.defaults do
		(merged :: any)[k] = v
	end
	local species = DATA.species[skin]
	if species ~= nil then
		for _, layer in { species.default, species[hatId] } do
			if layer ~= nil then
				for k, v in layer do
					(merged :: any)[k] = v
				end
			end
		end
	end
	return {
		scale = merged.scale,
		offset = Vector3.new(merged.offset[1], merged.offset[2], merged.offset[3]),
		tilt = CFrame.Angles(math.rad(merged.tilt[1]), 0, math.rad(merged.tilt[2])),
		hideEars = merged.hideEars == true,
	}
end

return HatFits
`;
fs.writeFileSync(path.join(DIR, '../roblox-game/game-src/client/HatFits.luau'), lua);
console.error('wrote HatFits.luau');
